### ISSUE TITLE
Add RunInBash to Chocolatey

### ISSUE THREAD

**Issue by luke-barnett** [neosmart/RunInBash#1]
RunInBash looks like an awesome little utility that I may start to depend on.

https://chocolatey.org/packages?q=runinbash

Can we get it added to chocolatey for easy installation and management of updates?

**Comment by SRGOM** [comment]
I came to the issues tab to create an issue to add it to chocolatey and that's the first issue right there.

**Comment by mqudsi** [comment]
Yup. Only waiting to add an installation routine to RunInBash that will register $ as an alias with the system so that Chocolatey and regular usage both share installation implementations.

**Comment by mqudsi** [comment]
https://chocolatey.org/packages/runinbash/0.1

**Comment by mqudsi** [comment]
Wheh! That took a while, but it's done: https://neosmart.net/blog/2017/runinbash-is-now-on-chocolatey/
