### ISSUE TITLE
Currently somewhat pointless

### ISSUE THREAD

**Issue by falfiya** [neosmart/RunInBash#5]
Unless `RunInBash` gets path translation support, which can already be done with `wslpath`, there's no advantage to using it. `wsl git status` for instance will work fine in PowerShell or cmd. Also, `bash.exe` has been deprecated. See [https://docs.microsoft.com/en-us/windows/wsl/interop](https://docs.microsoft.com/en-us/windows/wsl/interop)
![image](https://user-images.githubusercontent.com/22552895/52172651-ebd09000-2728-11e9-83c2-7ab74dccdc79.png)

**Comment by mqudsi** [comment]
It’s already in HEAD. You might might want to look at the already open issues.

**Comment by falfiya** [comment]
My bad, I had not checked the issues and code well enough.
